theme = "showfolio"
languageCode = "en-us"
baseurl = "https://rommelnunez.com"
title = "Rommel Nunez"


[params]
  name = "Rommel Nunez"
  description = "I am a filmmaker, photographer, engineer and content creator based in NYC."
  author = "Rommel Nunez"
  authorEmail = "rommelnunez@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = false

  copyright = "Copyright Â© 2023 - Rommel Nunez Â· All rights reserved."
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey ðŸ‘‹ I'm Rommel Nunez"
  tagline = "Filmmaker, Photographer, Engineer and Content Creator"
  description = "I produce/direct music videos, dance videos, films, design useful software and create online content."
  contact = "mailto:rommelnunezg@gmail.com"

[params.homepage.vimeo]
  username = "apvarun"
  videos = ["https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/edc196af-c54e-4cf2-8452-73f8fbddefa1.gif?ClientID=vimeo-core-prod&Date=1672994127&Signature=f9d150ae188de6df510fedd25946ce6f147b9215", "https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/53b55ff1-293e-40ad-93b9-786ac1b911ee.gif?ClientID=vimeo-core-prod&Date=1672996225&Signature=2687458d3eb8b9ca584027f0952d868fbf31be0c", "https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/5b0b21d5-3fcc-45f1-bd5c-4d86b460115b.gif?ClientID=vimeo-core-prod&Date=1672996560&Signature=8e4269094d502c4458488329c3348bbed61cbda1", "https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/7a329f34-6c6e-4249-97ed-b99af666a58f.gif?ClientID=vimeo-core-prod&Date=1672997035&Signature=c3d216c09142ea8d4063a27f7f50962d5ee9e87c","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/524adcb1-fcc5-4d9a-b8aa-6ba71ad198a8.gif?ClientID=vimeo-core-prod&Date=1672997276&Signature=a35578f248d4d78a5ee2126bdde230affb2584f7","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/2b47d35d-8daa-46b7-a376-c37d59a47bf6.gif?ClientID=vimeo-core-prod&Date=1672997536&Signature=82be85f9675605969288dfadd105cc3531964f78","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/8521cfaa-eb25-40a1-92f0-9fdbadecfe67.gif?ClientID=vimeo-core-prod&Date=1672997629&Signature=f9539cc4245ce31991584fadc97fc8fde0f9b50c","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/f1e09f12-d480-4d90-b420-b7f928e7d2d8.gif?ClientID=vimeo-core-prod&Date=1672997762&Signature=86e959a9d46845e1fad340212940af922fcba7c9","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/18f4e52f-5c25-48c4-b864-6aa98adae0a5.gif?ClientID=vimeo-core-prod&Date=1672998129&Signature=ec20a6c696919759ffb1ca7488ef3596d495c4bf"]
  links = ["774527458", "774847587", "774651309", "774646337","775167968","775138709","775156693","775379109","775145020"]

[params.homepage.resume]
  skills = ["Screenwriting", "Editing","Film Directing", "Production", "Film Coloring","Photography", "Product Management", "Software Engineering","Leadership","Applied AI/ML Modeling", "Applied NLP", "Reinforcement Learning Modeling", "Computational Data Analysis"]

[[params.homepage.resume.work]]
  name = "Columbia University"
  role = "Head Computer Teaching Assistant"
  duration = "September 2020 - Present"

[[params.homepage.resume.work]]
  name = "Ratrock Magazine"
  role = "President / Former Visuals Director"
  duration = "December 2020 - Present"

[[params.homepage.resume.work]]
  name = "Columbia Daily Spectator"
  role = "Senior Staff Photographer / Former Deputy City News Photo Editor"
  duration = "January 2020 - Present"

[[params.homepage.resume.work]]
  name = "JPMorgan Chase & Co."
  role = "Software Engineer Intern"
  duration = "June 2022 - August 2022"

[[params.homepage.resume.work]]
  name = "Lyn Health"
  role = "Product Manager Intern"
  duration = "June 2021 - August 2021"

[[params.homepage.resume.courses]]
  name = "Artificial Intelligence"
  provider = "Columbia University"
  duration = "January 2022 - May 2022"

[[params.homepage.resume.courses]]
  name = "Robot Learning"
  provider = "Columbia University"
  duration = "January 2022 - May 2022"

[[params.homepage.resume.courses]]
  name = "Computer Vision"
  provider = "Columbia University"
  duration = "September 2022 - December 2022"

[[params.homepage.resume.courses]]
  name = "Natual Language Processing"
  provider = "Columbia University"
  duration = "September 2021 - December 2021"

[[params.homepage.resume.courses]]
  name = "Spoken Language Processing"
  provider = "Columbia University"
  duration = "January 2023 - Present"

[[params.homepage.resume.courses]]
  name = "Cult and Exploitation Films"
  provider = "Columbia University"
  duration = "January 2021 - May 2021"

[params.homepage.social]
  instagram = "https://instagram.com/rommelnunezg"
  twitter = "https://twitter.com/rommelnunezg"
  tiktok = "https://www.tiktok.com/@rommelnunezg"
  linkedin = "https://linkedin.com/in/rommelnunez"
  github = "https://github.com/rommelnunez"
  

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

googleAnalytics = 'G-Y2V6RWWX0G'