theme = "showfolio"
languageCode = "en-us"
baseurl = "https://rommelnunez.com"
title = "Rommel Nunez"


[params]
  name = "Rommel Nunez"
  description = "I have over 6 years of experience creating digital content for clients such Skip Marley, Sarkodie, Eva Westphal, and many, many more."
  author = "Rommel Nunez"
  authorEmail = "rommelnunez@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright Â© 2023 - Rommel Nunez Â· All rights reserved."
  favicon = "favicon.ico"
[markup.goldmark.renderer]
  unsafe = true
[params.homepage]
  title = "Hey ðŸ‘‹ I'm Rommel Nunez"
  tagline = "Director, Producer, Photographer, Editor, and Content Strategist"
  description = "I have over 6 years of experience creating digital content. My clients include Skip Marley, Sarkodie, Black Hibiscus, Meta, Google, and Beekman 1802, among others."
  contact = "mailto:rommelnunezg@gmail.com"

[params.homepage.shorts]
  thumbnails = ["https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/fc2857aa-a8a1-4b35-b590-8bf7c38ae9a6.gif?ClientID=vimeo-core-prod&Date=1701844395&Signature=b49460713a35a2b94287ffac0371baa2a7389c23","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/616b125d-8fd3-45cb-b610-9c84d2fad29f.gif?ClientID=vimeo-core-prod&Date=1701843967&Signature=599b49c18bb0818b3014a891d93f67ba42a86975","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/cacdf0c1-d985-49db-8c80-b75bd44cab4d.gif?ClientID=vimeo-core-prod&Date=1701843820&Signature=4fe8996fc6de9c79f5ac66937e618ccc6e5b12ee","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/c2e509ac-e490-4fad-9fa7-fd12ac1a139a.gif?ClientID=vimeo-core-prod&Date=1701842675&Signature=84b37344250adf516b043c4d8465610a59eed2ee","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/11480978-222f-4c28-b333-b5d465bf5ac2.gif?ClientID=vimeo-core-prod&Date=1701842857&Signature=4b17f628c01986b167727bc9081b25077bf6dfa1","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/a3827700-9921-414a-a3b6-dbfa2789c551.gif?ClientID=vimeo-core-prod&Date=1701840278&Signature=c19d1fbe05d780437df877a0a94db5a7d905859c","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/90c62ca8-a9ce-4476-ba14-df24b6767f0c.gif?ClientID=vimeo-core-prod&Date=1701841262&Signature=bf77fc3c7182e1a519c3f9745b1e5e0480be0e80","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/ddb96e7d-0af1-4364-8515-0527ec7e2e4e.gif?ClientID=vimeo-core-prod&Date=1701841408&Signature=b8c9377f535fc35732457a9b34897fbdd59bd8d2","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/5d3c445b-81d7-46fa-ba26-5bccb2516a71.gif?ClientID=vimeo-core-prod&Date=1701841631&Signature=2b1b699e5ece9394063c8f4d9df5ca1b91a9c35c","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/70c6bec5-297b-4e1b-b2d1-5d95f01c99df.gif?ClientID=vimeo-core-prod&Date=1701842008&Signature=c5d74b65edbb08d11357a3c32f8ea7cb74e1f6b6","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/c3251c4e-57ee-4117-b78b-8a62c2f46f2b.gif?ClientID=vimeo-core-prod&Date=1701842159&Signature=4c1a88fa01a6db44d10d770ad8fcd6fa61cee92d"]
  links = ["https://www.instagram.com/reel/CzEbThpNvGm/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/CzrD1qoMmsF/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/C0FAmjxJE5M/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/C0SSMSiSt_u/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/CzZqWhZIUY4/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/CyeBcbQv-EX/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/Cyi86hngkyI/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/CyjYsWDP5wZ/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/Cyge8P1geLO/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/Cyg1ec2viHU/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==","https://www.instagram.com/reel/CyeOjp8P6FM/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA=="]

[params.homepage.vimeo]
  username = "rommelnunez"
  videos = ["https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/ba252dbc-630f-49bf-97c1-31d19e5e1986.gif?ClientID=vimeo-core-prod&Date=1701833395&Signature=1fc397b1f198dd8a6a0728a2faeb77d8297510b0","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/d0f418c0-82c8-46b2-bdc9-b879289fab56.gif?ClientID=vimeo-core-prod&Date=1701836532&Signature=f008a3de7cd148c886a85b72be78e8fbe3b35fd8","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/aeda6622-df7f-4311-b51b-c696be209c04.gif?ClientID=vimeo-core-prod&Date=1701836661&Signature=9139eb0e9713df58af19ba7089755ed1bebc69a9","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/18cb9cc0-0d55-442c-bcfa-85441c5bc5d3.gif?ClientID=vimeo-core-prod&Date=1691816079&Signature=2d8ae306b60d55880cd3aeae65d7ef4e60a4bd21","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/f55d94a4-86d8-4285-8dfb-bad5f07467e6.gif?ClientID=vimeo-core-prod&Date=1691817025&Signature=9ce2e4674453b8af1b6a4d5243ae4c88059f080d","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/11cfa269-6416-4c9e-ae40-b18a6961dcd1.gif?ClientID=vimeo-core-prod&Date=1690818016&Signature=f676c95e9ddcb6226c13291b9df70604b8456c74","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/31058704-67f6-488b-b692-fcd962f1af69.gif?ClientID=vimeo-core-prod&Date=1690817763&Signature=f281417be75e3404d1c10968fb61628562b7df49","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/edc196af-c54e-4cf2-8452-73f8fbddefa1.gif?ClientID=vimeo-core-prod&Date=1672994127&Signature=f9d150ae188de6df510fedd25946ce6f147b9215", "https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/53b55ff1-293e-40ad-93b9-786ac1b911ee.gif?ClientID=vimeo-core-prod&Date=1672996225&Signature=2687458d3eb8b9ca584027f0952d868fbf31be0c", "https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/5b0b21d5-3fcc-45f1-bd5c-4d86b460115b.gif?ClientID=vimeo-core-prod&Date=1672996560&Signature=8e4269094d502c4458488329c3348bbed61cbda1", "https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/7a329f34-6c6e-4249-97ed-b99af666a58f.gif?ClientID=vimeo-core-prod&Date=1672997035&Signature=c3d216c09142ea8d4063a27f7f50962d5ee9e87c","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/524adcb1-fcc5-4d9a-b8aa-6ba71ad198a8.gif?ClientID=vimeo-core-prod&Date=1672997276&Signature=a35578f248d4d78a5ee2126bdde230affb2584f7","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/2b47d35d-8daa-46b7-a376-c37d59a47bf6.gif?ClientID=vimeo-core-prod&Date=1672997536&Signature=82be85f9675605969288dfadd105cc3531964f78","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/8521cfaa-eb25-40a1-92f0-9fdbadecfe67.gif?ClientID=vimeo-core-prod&Date=1672997629&Signature=f9539cc4245ce31991584fadc97fc8fde0f9b50c","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/f1e09f12-d480-4d90-b420-b7f928e7d2d8.gif?ClientID=vimeo-core-prod&Date=1672997762&Signature=86e959a9d46845e1fad340212940af922fcba7c9","https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/18f4e52f-5c25-48c4-b864-6aa98adae0a5.gif?ClientID=vimeo-core-prod&Date=1672998129&Signature=ec20a6c696919759ffb1ca7488ef3596d495c4bf"]
  links = ["890913736","891702247","891702642","853902441","850209543","850047134","830330487","774527458", "774847587", "774651309", "774646337","775167968","775138709","775156693","775379109","775145020"]

[params.homepage.youtube]
  username = "apvarun"
  videos = ["https://s3.gifyu.com/images/Editorial_Film_Photographywith_a_Digital_Camera.gif"]
  links = ["watch?v=8nBqZ6IgVeY&t=16s"]


[params.homepage.resume]
  skills = ["Adobe Premiere Pro", "Adobe After Effects", "Davinci Resolve", "Adobe Photoshop", "Adobe Lightroom","Screenwriting", "Editing","Film Directing", "Production", "Film Coloring","Photography", "Product Management", "Software Engineering","Leadership","Applied AI/ML Modeling", "Applied NLP", "Reinforcement Learning Modeling", "Computational Data Analysis"]

[[params.homepage.resume.work]]
  name = "Columbia University"
  role = "Head Computer Teaching Assistant"
  duration = "September 2020 - Present"

[[params.homepage.resume.work]]
  name = "Ratrock Magazine"
  role = "President / Former Visuals Director"
  duration = "December 2020 - Present"

[[params.homepage.resume.work]]
  name = "Columbia Daily Spectator"
  role = "Senior Staff Photographer / Former Deputy City News Photo Editor"
  duration = "January 2020 - Present"

[[params.homepage.resume.work]]
  name = "JPMorgan Chase & Co."
  role = "Software Engineer Intern"
  duration = "June 2022 - August 2022"

[[params.homepage.resume.work]]
  name = "Lyn Health"
  role = "Product Manager Intern"
  duration = "June 2021 - August 2021"

[[params.homepage.resume.courses]]
  name = "Artificial Intelligence"
  provider = "Columbia University"
  duration = "January 2022 - May 2022"

[[params.homepage.resume.courses]]
  name = "Robot Learning"
  provider = "Columbia University"
  duration = "January 2022 - May 2022"

[[params.homepage.resume.courses]]
  name = "Computer Vision"
  provider = "Columbia University"
  duration = "September 2022 - December 2022"

[[params.homepage.resume.courses]]
  name = "Natual Language Processing"
  provider = "Columbia University"
  duration = "September 2021 - December 2021"

[[params.homepage.resume.courses]]
  name = "Spoken Language Processing"
  provider = "Columbia University"
  duration = "January 2023 - Present"

[[params.homepage.resume.courses]]
  name = "Cult and Exploitation Films"
  provider = "Columbia University"
  duration = "January 2021 - May 2021"

[params.homepage.social]
  instagram = "https://instagram.com/rommelnunezg"
  twitter = "https://twitter.com/rommelnunezg"
  tiktok = "https://www.tiktok.com/@rommelnunezg"
  linkedin = "https://linkedin.com/in/rommelnunez"
  github = "https://github.com/rommelnunez"
  

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

googleAnalytics = 'G-Y2V6RWWX0G'